<?php

declare( strict_types=1 );

namespace ArtisanPackUI\SecurityAnalytics\Analytics\Reports;

use ArtisanPackUI\SecurityAnalytics\Analytics\Reports\Contracts\ReportInterface;

abstract class AbstractReport implements ReportInterface
{
    /**
     * @var array<string, mixed>
     */
    protected array $options;

    /**
     * @param  array<string, mixed>  $options
     */
    public function __construct( array $options = [] )
    {
        $this->options = array_merge( $this->getDefaultOptions(), $options );
    }

    /**
     * {@inheritdoc}
     */
    public function toHtml( array $data ): string
    {
        $title       = htmlspecialchars( $this->getTitle(), ENT_QUOTES, 'UTF-8' );
        $generatedAt = now()->format( 'Y-m-d H:i:s T' );
        $periodStart = $this->options['start_date']->format( 'Y-m-d' );
        $periodEnd   = $this->options['end_date']->format( 'Y-m-d' );

        $html = <<<HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{$title}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        h1 { color: #1a1a1a; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
        h2 { color: #374151; margin-top: 30px; }
        h3 { color: #4b5563; }
        .header { margin-bottom: 30px; }
        .meta { color: #6b7280; font-size: 14px; margin-bottom: 20px; }
        table { border-collapse: collapse; width: 100%; margin: 20px 0; }
        th, td { border: 1px solid #e5e7eb; padding: 12px; text-align: left; }
        th { background-color: #f3f4f6; font-weight: 600; }
        tr:nth-child(even) { background-color: #f9fafb; }
        .severity-critical { color: #dc2626; font-weight: bold; }
        .severity-high { color: #ea580c; font-weight: bold; }
        .severity-medium { color: #ca8a04; }
        .severity-low { color: #2563eb; }
        .severity-info { color: #6b7280; }
        .stat-card { display: inline-block; padding: 20px; margin: 10px; background: #f3f4f6; border-radius: 8px; min-width: 150px; }
        .stat-value { font-size: 32px; font-weight: bold; color: #1f2937; }
        .stat-label { color: #6b7280; font-size: 14px; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{$title}</h1>
        <div class="meta">
            <p>Report Period: {$periodStart} to {$periodEnd}</p>
            <p>Generated: {$generatedAt}</p>
        </div>
    </div>
    {$this->renderHtmlContent( $data )}
    <div class="footer">
        <p>This report was automatically generated by the Security Analytics system.</p>
        <p>For questions or concerns, please contact your security team.</p>
    </div>
</body>
</html>
HTML;

        return $html;
    }

    /**
     * {@inheritdoc}
     */
    public function toCsv( array $data ): string
    {
        $rows = $this->getCsvRows( $data );

        if ( empty( $rows ) ) {
            return '';
        }

        $output = fopen( 'php://temp', 'r+' );

        // Write headers
        fputcsv( $output, array_keys( $rows[0] ?? [] ) );

        // Write data
        foreach ( $rows as $row ) {
            fputcsv( $output, $row );
        }

        rewind( $output );
        $csv = stream_get_contents( $output );
        fclose( $output );

        return $csv;
    }

    /**
     * {@inheritdoc}
     */
    public function toPdf( array $data ): string
    {
        // For PDF generation, we return the HTML content
        // In production, use a library like DomPDF or wkhtmltopdf
        // This is a placeholder that returns HTML
        return $this->toHtml( $data );
    }

    /**
     * Get default options for the report.
     *
     * @return array<string, mixed>
     */
    protected function getDefaultOptions(): array
    {
        return [
            'period_days' => 7,
            'start_date'  => now()->subDays( 7 )->startOfDay(),
            'end_date'    => now()->endOfDay(),
        ];
    }

    /**
     * Get the report title.
     */
    abstract protected function getTitle(): string;

    /**
     * Render the main HTML content.
     *
     * @param  array<string, mixed>  $data
     */
    abstract protected function renderHtmlContent( array $data ): string;

    /**
     * Get rows for CSV export.
     *
     * @param  array<string, mixed>  $data
     *
     * @return array<int, array<string, mixed>>
     */
    abstract protected function getCsvRows( array $data ): array;

    /**
     * Render a data table in HTML.
     *
     * @param  array<int, array<string, mixed>>  $rows
     * @param  array<int, string>|null  $headers
     */
    protected function renderTable( array $rows, ?array $headers = null ): string
    {
        if ( empty( $rows ) ) {
            return '<p>No data available.</p>';
        }

        $headers = $headers ?? array_keys( $rows[0] ?? [] );

        $html = '<table><thead><tr>';
        foreach ( $headers as $header ) {
            $html .= '<th>' . htmlspecialchars( ucwords( str_replace( '_', ' ', $header ) ) ) . '</th>';
        }
        $html .= '</tr></thead><tbody>';

        foreach ( $rows as $row ) {
            $html .= '<tr>';
            foreach ( $headers as $key ) {
                $value = $row[ $key ] ?? '';
                $class = '';

                // Add severity class if applicable
                if ( 'severity' === $key ) {
                    $class = ' class="severity-' . htmlspecialchars( $value ) . '"';
                }

                $displayValue = is_array( $value ) ? json_encode( $value ) : htmlspecialchars( (string) $value );
                $html .= "<td{$class}>{$displayValue}</td>";
            }
            $html .= '</tr>';
        }

        $html .= '</tbody></table>';

        return $html;
    }

    /**
     * Render stat cards in HTML.
     *
     * @param  array<string, mixed>  $stats
     */
    protected function renderStatCards( array $stats ): string
    {
        $html = '<div class="stat-cards">';

        foreach ( $stats as $label => $value ) {
            $displayLabel = ucwords( str_replace( '_', ' ', $label));
            $html .= <<<CARD
            <div class="stat-card">
                <div class="stat-value">{$value}</div>
                <div class="stat-label">{$displayLabel}</div>
            </div>
            CARD;
        }

        $html .= '</div>';

        return $html;
    }
}
